### ISSUE TITLE
Style for keyboard keys

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#100]
@datacarpentry has some CSS for keyboard keys:

![screenshot_2016-09-02_13-50-45](https://cloud.githubusercontent.com/assets/1506457/18204394/7828b9ec-7114-11e6-8262-fd14154910ef.png)

Can we have it?

**Comment by gvwilson** [comment]
How do I express this in Markdown without using HTML tags?

**Comment by rgaiacs** [comment]
~~~
$ kramdown <<EOF
`TAB`{: .keyboard }
EOF
<p><code class="keyboard">TAB</code></p>
~~~

, as describe at http://kramdown.gettalong.org/quickref.html#inline-attributes, and

~~~
.keyboard {
    padding: 2px 4px;
    font-size: 90%;
    color: #fff;
    background-color: #333;
    border-radius: 3px;
    -webkit-box-shadow: inset 0 -1px 0 rgba(0,0,0,.25);
    box-shadow: inset 0 -1px 0 rgba(0,0,0,.25);
    font-family: monospace;
}

**Comment by gvwilson** [comment]
Ick.

**Comment by brandoncurtis** [comment]
There has been some confusion about keyboard key name formatting, in e.g. swcarpentry/shell-novice/pull/561

Regarding the proposal above:

<pre>when the user types a command and then presses `ENTER`{: .keyboard } ...</pre>

That doesn't look so bad to me!  @gvwilson, is that definitely a no-go for you?

We have this [in StackExchange in the form of an HTML tag][sx], though I gather that HTML tags should be avoided in SWC material.

The alternative would be to add something to the SWC styleguide regarding formatting of keyboard key names, such as "all caps and surrounded by backticks":

<pre>`ENTER`</pre>

(Are the contents of https://github.com/swcarpentry/lesson-example the definitive styleguide?)

[sx]: https://meta.stackexchange.com/questions/26207/how-can-i-format-as-keyboard-keys

**Comment by brandoncurtis** [comment]
I explored this a little further and *ENTER*{: .keyboard } is preferred over `ENTER`{: .keyboard} so that Unicode string references work for e.g. the arrow keys.

It looks like this:
![keys-demo](https://user-images.githubusercontent.com/2591290/29035841-e73333ec-7b51-11e7-9772-6b2a44b12127.png)


With this CSS:

```css
// keyboard key name style, from StackExchange
.keyboard {
    display: inline-block;
    margin: 0 .1em;
    padding: .1em .6em;
    font-family: Arial,"Helvetica Neue",Helvetica,sans-serif;
    font-size: 11px;
    line-height: 1.4;
    color: #242729;
    text-shadow: 0 1px 0 #FFF;
    background-color: #e1e3e5;
    border: 1px solid #adb3b9;
    border-radius: 3px;
    box-shadow: 0 1px 0 rgba(12,13,14,0.2), 0 0 0 2px #FFF inset;
    white-space: nowrap;
    font-style: normal;
}
```
