### ISSUE TITLE
Not getting Travis CI to build with ruby > 2.5.8 requirement 

### ISSUE THREAD

**Issue by klieret** [swcarpentry/styles#477]
After the required Ruby version in the Gemfile was bumped to ``>=2.5.8`` (following ``gh-pages``?), Travis won't build anymore under Xenial (because it has only 2.5.3 precompiled, see [here](https://docs.travis-ci.com/user/reference/xenial/#ruby-support)). However turning to Bionic Ubuntu works for the Ruby version, but there are other issues (in particular ``nokogiri`` won't work).

I have played around a bit (https://github.com/hsf-training/hsf-training-docker/pull/4), but haven't found a satisfactory solution.

Does anyone have any idea for how to fix this?

**Comment by klieret** [comment]
Okay, actually I managed to get it to build for us (see the linked PR), but I expect this to be an issue for others. Also I removed things required for the ``R`` support which errored. 

Let me know if there's any more proper way of doing this!

**Comment by fmichonneau** [comment]
Thanks for letting us know. Could you please open a PR against this repository with your changes?

**Comment by klieret** [comment]
We fixed it among others by removing everything relating to ``R`` (which you probably need).

I have tried to reenable the ``R`` stuff and arrive at:

```yml
dist: bionic  # Ubuntu 18.04 for new ruby version
language: python
python: 3.7
branches:
  only:
  - gh-pages
  - /.*/
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - echo "deb https://cran.rstudio.com/bin/linux/ubuntu bionic/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -y
  - rvm default
  - gem install json kramdown jekyll
install:
  - pip install pyyaml
script:
  - bundle config build.nokogiri --use-system-libraries
  - make lesson-check-all
  - make --always-make site
```

However this fails with 

```
E: The repository 'https://cran.rstudio.com/bin/linux/ubuntu bionic/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
The command "sudo apt-get update -y" failed and exited with 100 during .
```

So something seems to be wrong with the bionic release of rstudio?

**Comment by klieret** [comment]
Let me ping @rgaiacs and @agitter  who also worked on this.

**Comment by agitter** [comment]
@klieret I don't have any great ideas.  My only updates to the Travis CI install script were pretty minor.

I was hoping that [Travis Rubies](https://rubies.travis-ci.org/usage) would provide an easy way to update the Ruby version.  However, I only see support through `ruby-2.7.1`.

**Comment by klieret** [comment]
Ah, but ``ruby-2.7.1`` would be enough, so I could try again with the ``16.04`` ubuntu (for which the rstudio installation worked).

Btw, why do we install rstudio though? As far as I understood, that's an R IDE. Seems strange that we need that for CI...

**Comment by fmichonneau** [comment]
We don't install the Rstudio IDE, just R. We use one of the mirrors to download R that happens to be hosted by Rstudio (the company).

**Comment by klieret** [comment]
Hmm, I just tried

```yml
# Travis CI is only used to check the lesson and is not involved in its deployment
dist: xenial  # Ubuntu 16.04 (required for python 3.7)
language: python
python: 3.7
branches:
  only:
  - gh-pages
  - /.*/
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -y
  - sudo apt-get install --allow-unauthenticated r-base
  - sudo Rscript -e "install.packages('knitr', repos = 'https://', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('stringr', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('checkpoint', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - sudo Rscript -e "install.packages('ggplot2', repos = 'https://cran.rstudio.com', dependencies = TRUE)"
  - rvm default
  - ruby-install --binary -M https://rubies.travis-ci.org/ ruby 2.7.1
  - gem install json kramdown jekyll bundler
install:
  - pip install pyyaml
script:
  - make lesson-check-all
  - make --always-make site
```

Unfortunately the ``ruby-install`` command that is advertised [here](https://rubies.travis-ci.org/usage) "after a certain PR is merged" doesn't seem to work yet. So I think I'm out of ideas for how to get this working without sacrificing ``R`` support. 

(Also installing the ``R`` packages takes forever (more than 10 minutes!))
